### ISSUE TITLE
Validation question collection

### ISSUE THREAD

**Issue by andrewjneumann** [National-COVID-Cohort-Collaborative/Synthetic-Clinical-Data#6]

**Comment by andrewjneumann** [comment]
Current running list: https://docs.google.com/document/d/15WAr-cIxx0ufjfLJSt5pv5songvDY5pKuHoB7s1QQaA/edit

**Comment by tmdillon** [comment]
Created this Google doc:  https://docs.google.com/document/d/1t-bzx_YVmRjJSu466zBJUoomwJBzYhJvZbetwdYtUP8/edit
